### ISSUE TITLE
Path of Building SSL connection  error

### ISSUE THREAD

**Issue by WeirdStu** [Openarl/PathOfBuilding#1609]
Well i have the ssl connection problem with the pastebin links. iv tried everything redownloaded the program 4 times i dont own any anti virus problem so thats not the issue i had no problems when i played the game last month im not sure what can be the cause of it if anyone knows something about it ill appreciate it  
Thank you

**Comment by Supportic** [comment]
I also have this problem but you can always open the pastebin and copy the whole code in the textbox next to the import button.

**Comment by xerance** [comment]
same, started recently doe. worked just fine last league

**Comment by Stolver** [comment]
Same.. happening to 3 computers in my house.  Interestingly, it happened about the same time that we all updated to Win10 1903 (the large windows update) - not sure if related, but a thought.

**Comment by Radagast** [comment]
For me, the reason this fails with HTTPS and not HTTP is that, for some reason, PoB needs LSASS.EXE to have Internet access. This really shouldn't be necessary.

**Comment by stanec1** [comment]
I have this problem since some days ago. I can't import my character from poe. I tried to disable antivirus and the firewall. Tried with 2 machines with w7 and different ISP. I still got the same error (SSL connect error). I only could import in another machine with w10.

**Comment by goldaryn** [comment]
> For me, the reason this fails with HTTPS and not HTTP is that, for some reason, PoB needs LSASS.EXE to have Internet access. This really shouldn't be necessary.

Allowing LSASS.EXE in my firewall fixed this issue for me, too. Thanks!

**Comment by xerance** [comment]
whats LSASS.EXE? i dont even have this thing

**Comment by Radagast** [comment]
@xerance 

LSASS is a Windows System Service (Local Security Authority Subsystem Service) it's used for managing various security related policies on Windows. It shouldn't be used here for SSL connections. 

For me and  goldaryn  it wasn't allowed through the firewall, so the connection failed. It really doesn't need Internet access and should be fixed.

**Comment by Stolver** [comment]
LSASS seems to be the target of viruses and malware. I am uncomfortable just giving it a free ride through my firewall.

**Comment by stanec1** [comment]
I resolved my issue with LSASS too, i forgot to refresh my firewall rules before. I always leave this application blocked. PoB shound't rely on that to make connections.

**Comment by aiolos01** [comment]
I have the same problem and I agree that LSASS shouldn't require internet access. In the meantime just change https to http in the pastebin link as a temporary solution.
Of course this doesn't fix the same problem occurring when importing your own characters.

**Comment by Galldar** [comment]
Has there been a fix for the SSL issue people have been having with PoB if so could someone drop me a link thank you

**Comment by goldaryn** [comment]
Here's a workaround for the issue where you can't import characters from poe.com:

1) go to the releases page - https://github.com/Openarl/PathOfBuilding/releases
2) download and extract the .zip version. you must use this version for the workaround.
3) edit \Classes\ImportTab.lua
4) search for all references to https://www.pathofexile.com and change to http://www.pathofexile.com

Obvs. https is better than http and this is at our own risk, but it seems to work. Same should also work for pastebin links.

**Comment by rroriz** [comment]
If you have Kaspersky enabled, deactivate it just to import, then reactivate it

**Comment by Tetuev** [comment]
> If you have Kaspersky enabled, deactivate it just to import, then reactivate it

It's work , Kaspersky disable accsess to LSASS.EXE from Path of Building , because it dangerous. Just pause protection for 1 min and enter the pastbin code or make your code of your build.

Or you can use decision from reddit:

1.Double click on the Kaspersky icon on the status bar.
2.Click on the gear icon ok the lower left to open settings.
3.Open the additional tab and click on network.
4.Scroll downwards and click on the manage exclusions option.
5.Click the add button.
6.Type pastebin.com and click on the add button.

**Comment by imthenats** [comment]
I just added Path of Building as a Trusted Application in Kaspersky. Checked the 1st four boxes. 
I couldn't get the URL exceptions to fix the issue. I tried every combination for the Web Filter. The instructions Tetuev explained may not work as the Program has changed.

**Comment by xerance** [comment]
To get pob to work with pastebin you need to add pob to trusted application AND pastebin to trusted adresses.

https://puu.sh/IGNT8/34820bcc2c.mp4

works for both the community fork and this original version.

do note: adding trusted addresses seems to be a hit or miss, works on my pc without it but not on my laptop.
